language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: VddmbRSzTnoPDJP4sCtlLuHUYY5TNyPtym7retoS+6SGsky6XkhRua8FPiSIYRFyswp4gWr9i5Hm47NLaxmIqfw4teahQB74KmAvIkpmdOMZNw48GXhlbloDsNtvWO6J92E8sfCqPb+VzIrhViobt+nMUwb0bZKBDxGFw2y60EGRO8mv1uwpL4d3diAVLGniyE74fiINiYTo3o7sEDEWla8LNm1KwFOp3knmRZCt2DG8v9APv/u9xZZgNVS427Ohuz59KrcBIOkD42OUeYVvSw/gzdkk6hOvzb0tiq65hoZMPEkWZT2BrqK2b7Y3KO/KLd1SQHPSQ2LzmlsmAU73ED6LhMwTDZLHaipj+i3ks5uKbISEZ2GNEVgyU6w1R0azHOOFVzy14aabMRZf21uqT7hGludBjIz7RdR8SPuB7pbtZpEr26wbBk0RToqTsZnmIekXSGdZDphGnjRBTB34kK2Tdkf5YK5arMT7hUvJSKgSgvaCNDwVdpbhKTkl3wTkz9qXfxuNkvte1DFkWvEp55S/pss9AmVliG/JqAmIpUzEI3dG+oIkeV/RbPTrVVroF+JvqvNDzx9Qdan304r6nbqCLY/4Op66bpHIoeLLWK6JmHHZE4XgE6C2L64qGv4bG75f9vErbyBw8uKSYdpm1996kyQ/lHBcMSeotopgbX8=
  app: mean_stack_deploy
  on:
    repo: usnaik/mean_stack_deploy
  skip_cleanup: 'true'
